PATH = "/base/production/cameraisptester"
ENABLE = true
INFO = false
LIMIT = false
DEPENDS = "cameraisptester"

command = "cameraisptester.sh"
run_times = 1
run_alone = true
testcase_run_once_time = "60"

need_to_confirm_the_result:bool = false
