/**

* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the people's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __RPBUF_AUDIO_CRTL_H__
#define __RPBUF_AUDIO_CRTL_H__

#define RPBUF_LEN_MAX			(0x100000)

#define RPBUF_CTRL_ID					(0)

typedef enum {
	RPBUF_CTL_NONE 	= 0,
	RPBUF_CTL_INIT,
	RPBUF_CTL_CONFIG,            // config algo param
	RPBUF_CTL_START,             // start algo
	RPBUF_CTL_PAUSE,             // pause algo
	RPBUF_CTL_RESUME,            // resume algo
	RPBUF_CTL_STOP,              // stop algo
	RPBUF_CTL_RELEASE,           // release algo
	RPBUF_CTL_ENABLE_ALG,        // enable algorithm
	RPBUF_CTL_DUMP_MERGE_DATA,   // input data(2 mic + 1 ref/ 6ch eq) + output data (aec / 6ch eq)
	RPBUF_CTL_START_ACK,         // start algo ack
	RPBUF_CTL_LOW_POWER_MODE,    // low power mode
	RPBUF_CTL_NUM,
}RPBUF_CTRL_TYPE;

typedef enum {
	RPBUF_ALGO_NONE 	= 0,
	RPBUF_ALGO_AEC,            // aec algo
	RPBUF_ALGO_AEC_DOWNLINK,   // aec downlink algo param
	RPBUF_ALGO_EQ,             // eq algo param
	RPBUF_ALGO_AMP,            // audio module process algo param
	RPBUF_ALGO_RECORD,         // audio record
	RPBUF_ALGO_NUM,
}RPBUF_ALGO_TYPE;

typedef enum  {
	RPBUF_AUDIO_DSP_RECORD_MODE_NORMAL = 0,
	RPBUF_AUDIO_DSP_RECORD_MODE_LOW_POWER,
} AUDIO_RECORD_MODE;


/** The RPBUF_ERROR_TYPE enumeration defines the standard RPBUF Errors.
 *  These errors should cover most of the common failure cases.
 */
typedef enum RPBUF_ERROR_TYPE
{
	RPBUF_ERROR_NONE = 0,

	RPBUF_ERROR_INIT_FAIL = (long) 0x60001000,

	RPBUF_ERROR_CONFIG_FAIL = (long) 0x60001001,

	RPBUF_ERROR_START_FAIL = (long) 0x60001002,

	RPBUF_ERROR_PAUSE_FAIL = (long) 0x60001003,

	RPBUF_ERROR_RESUME_FAIL = (long) 0x60001004,

	RPBUF_ERROR_STOP_FAIL = (long) 0x60001005,

	RPBUF_ERROR_RELEASE_FAIL = (long) 0x60001006,

	RPBUF_ERROR_ENABLE_ALG_FAIL = (long) 0x60001007,

	RPBUF_ERROR_DUMP_MERGE_DATA = (long) 0x60001008,

	/** There was an error, but the cause of the error could not be determined */
	RPBUF_ERROR_UNDEFINED = (long)0x70000000,
	RPBUF_ERROR_MAX = 0x7FFFFFFF
} RPBUF_ERROR_TYPE;



#endif
