/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the people's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef STD_DEFS_H
#define STD_DEFS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef unsigned int U32;

/*! error code  */
typedef enum sk_status_code_e {
	AW_SUCCESS = 0,
	AW_ERROR_BAD_PARAMETER, /* Bad parameter passed       */
	AW_ERROR_NO_MEMORY, /* Memory allocation failed   */
	AW_ERROR_UNKNOWN_DEVICE, /* Unknown device name        */
	AW_ERROR_ALREADY_INITIALIZED, /* Device already initialized */
	AW_ERROR_NO_FREE_HANDLES, /* Cannot open device again   */
	AW_ERROR_INVALID_HANDLE, /* Handle is not valid        */
	AW_ERROR_INVALID_ID, /* ID is not valid        */
	AW_ERROR_FEATURE_NOT_SUPPORTED, /* Feature unavailable        */
	AW_ERROR_INTERRUPT_INSTALL, /* Interrupt install failed   */
	AW_ERROR_INTERRUPT_UNINSTALL, /* Interrupt uninstall failed */
	AW_ERROR_TIMEOUT, /* Timeout occured            */
	AW_ERROR_DEVICE_BUSY, /* Device is currently busy   */
	AW_ERROR_NO_INIT, /* not init    */
	AW_ERROR_MAX_COUNT, /* that more than max count    */
	AW_ERROR_INSUFFICIENT_BUFFER, /* insufficient buffer    */
	AW_FAILED, /* UNKNOWN ERROR   */
	AW_STATUS_ENABLE,
	AW_STATUS_DISABLE,
	AW_ERROR_DEVICE_NOT_ONLINE,
	AW_ERROR_CLOSED_BY_REMOTE
} status_code_t;

#ifdef __cplusplus
}
#endif

#endif /*STD_DEFS_H*/

/*eof*/
