#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=1
STOP=98

boot() {
	[ -f /etc/config/mods.early.dep ] && \
			/usr/sbin/parallel_insmod /etc/config/mods.early.dep /lib/modules/$(uname -r)
}
