/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the people's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __MJSON_SYSKEY_H
#define __MJSON_SYSKEY_H
/* 详细说明见 tinatest/doc/CONFIG.txt */

/* global */
#define SYSKEY_GLOBAL_LIMIT_RUN_CNT_UP_TO "run_cnt_up_to"
#define SYSKEY_GLOBAL_LIMIT_TINATEST_RUN_TIME "tinatest_run_time"
// common
#define SYSKEY_GLOBAL_INFO_COLLECTD_INTERVAL_SEC "collectd_interval_sec"
#define SYSKEY_GLOBAL_INFO_COLLECTD_OUTDIR "outdir"
#define SYSKEY_GLOBAL_INFO_COLLECTD_ENABLE "enable"
#define SYSKEY_GLOBAL_INFO_COLLECTD_REPORT_TO_ABSOLUTE "report_to_absolute"
#define SYSKEY_GLOBAL_INFO_COLLECTD_REPORT_TO_PERCENTAGE "report_to_percentage"
#define SYSKEY_GLOBAL_INFO_COLLECTD_MATCH_SELECT_OR_IGNORE "select_or_ignore"
#define SYSKEY_GLOBAL_INFO_COLLECTD_MATCH "match"
#define SYSKEY_GLOBAL_INFO_COLLECTD_MATCH_ALL "ALL"
#define SYSKEY_GLOBAL_INFO_COLLECTD_MATCH_SELECT "select"
#define SYSKEY_GLOBAL_INFO_COLLECTD_MATCH_IGNORE "ignore"

// personal
//  测试项名
#define SYSKEY_GLOBAL_INFO_COLLECTD_CSV "collectd_csv"
#define SYSKEY_GLOBAL_INFO_COLLECTD_RRDTOOL "collectd_rrdtool"
#define SYSKEY_GLOBAL_INFO_COLLECTD_CPU "collectd_cpu"
#define SYSKEY_GLOBAL_INFO_COLLECTD_MEMORY "collectd_memory"
#define SYSKEY_GLOBAL_INFO_COLLECTD_DF "collectd_df"
#define SYSKEY_GLOBAL_INFO_COLLECTD_DISK "collectd_disk"
#define SYSKEY_GLOBAL_INFO_COLLECTD_FILECOUNT "collectd_filecount"
#define SYSKEY_GLOBAL_INFO_COLLECTD_PING "collectd_ping"
// 测试项私人属性
#define SYSKEY_GLOBAL_INFO_COLLECTD_DF_MATCH_DEVICE "device"
#define SYSKEY_GLOBAL_INFO_COLLECTD_DF_MATCH_MOUNTPOINT "mountpoint"
#define SYSKEY_GLOBAL_INFO_COLLECTD_DF_MATCH_FSTYPE "fstype"
#define SYSKEY_GLOBAL_INFO_COLLECTD_DISK_MATCH_DISK "disk_regular_expression"
#define SYSKEY_GLOBAL_INFO_COLLECTD_FILECOUNT_DIRECTORY "directory"
#define SYSKEY_GLOBAL_INFO_COLLECTD_FILECOUNT_INCLUDE_HIDDEN "include_hidden"
#define SYSKEY_GLOBAL_INFO_COLLECTD_FILECOUNT_INCLUDE_SUBDIR "include_subdir"
#define SYSKEY_GLOBAL_INFO_COLLECTD_FILECOUNT_MATCH_NAME "name"
#define SYSKEY_GLOBAL_INFO_COLLECTD_FILECOUNT_MATCH_SIZE "size"
#define SYSKEY_GLOBAL_INFO_COLLECTD_FILECOUNT_MATCH_MTIME "mtime"
#define SYSKEY_GLOBAL_INFO_COLLECTD_PING_HOST "host"
#define SYSKEY_GLOBAL_INFO_COLLECTD_PING_SEND_INTERVAL_SEC "send_interval_sec"
#define SYSKEY_GLOBAL_INFO_COLLECTD_PING_TIMEOUT_SEC "timeout_sec"
#define SYSKEY_GLOBAL_INFO_COLLECTD_PING_MAX_TTL "max_ttl"

/* local */
#define SYSKEY_LOCAL_LIMIT_EXIT_TINATEST_WHEN_FAIL "exit_tinatest_when_failed"
#define SYSKEY_LOCAL_LIMIT_RUN_TIMES "run_times"
#define SYSKEY_LOCAL_LIMIT_RUN_ALONE "run_alone"
#define SYSKEY_LOCAL_LIMIT_RUN_PARALLEL "run_parallel"
#define SYSKEY_LOCAL_LIMIT_MAY_REBOOT "may_reboot"
#define SYSKEY_LOCAL_LIMIT_TESTCASE_RUN_ONCE_TIME "testcase_run_once_time"
#define SYSKEY_LOCAL_LIMIT_TESTCASE_RUN_TIME "testcase_run_time"
#define SYSKEY_LOCAL_LIMIT_TIMEOUT_AS_FAILED "timeout_as_failed"
#define SYSKEY_LOCAL_LIMIT_EXIT_ONCE_FAILED "exit_once_failed"
#define SYSKEY_LOCAL_INFO_DATE "date"
#define SYSKEY_LOCAL_INFO_RESOURCE "resource"
#define SYSKEY_LOCAL_INFO_REAL_TIME_LOG "real_time_log"

/*任务属性配置关键字*/
#define SYSKEY_TASK_COMMAND "command"
#define SYSKEY_TASK_ENABLE "enable"
#define SYSKEY_TASK_STDIN "stdin"
#define SYSKEY_TASK_FSTDIN "fstdin"

//默认值(无则默认为0)
#define DEFAULT_GLOBAL_LIMIG_RUN_CNT_UP_TO 10
#define DEFAULT_GLOBAL_LIMIG_TINATEST_RUN_TIME_SEC (356 * 24 * 60 * 60)
#define DEFAULT_GLOBAL_OUTPATH "/mnt/UDISK/collectd"
#define DEFAULT_GLOBAL_COLLECTD_INTERVAL_SEC 2
#define DEFAULT_LOCAL_LIMIT_RUN_TIMES 1
#define DEFAULT_LOCAL_TESTCASE_RUN_ONCE_TIME_SEC (24 * 60 * 60)
#define DEFAULT_LOCAL_TESTCASE_RUN_TIME_SEC (24 * 60 * 60)

#endif
